### ISSUE TITLE
Failure building docker container

### ISSUE THREAD

**Issue by msche** [UniKnow/neurosim-ide#1]
**Describe the bug**

When executing `./mvnw install` creation of docker container fails with the following exception:

```
[INFO] DOCKER> [91merror /usr/src/client/node_modules/drivelist: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /usr/src/client/node_modules/drivelist
Output:
prebuild-install WARN install No prebuilt binaries found (target=10.18.0 runtime=node arch=x64 platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.18.0 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python"
gyp http GET https://unofficial-builds.nodejs.org/download/release/v10.18.0/node-v10.18.0-headers.tar.gz
gyp http 200 https://unofficial-builds.nodejs.org/download/release/v10.18.0/node-v10.18.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack ZlibError: zlib: unexpected end of file
gyp ERR! stack     at Unzip.write (/usr/src/client/node_modules/minizlib/index.js:147:22)
gyp ERR! stack     at Unzip.flush (/usr/src/client/node_modules/minizlib/index.js:98:10)
gyp ERR! stack     at Unzip.end (/usr/src/client/node_modules/minizlib/index.js:104:10)
gyp ERR! stack     at Unpack.end (/usr/src/client/node_modules/tar/lib/parse.js:421:21)
gyp ERR! stack     at IncomingMessage.onend (_stream_readable.js:670:10)
gyp ERR! stack     at Object.onceWrapper (events.js:286:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:203:15)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1143:12)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/src/client/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/src/client/node_modules/drivelist
gyp ERR! node -v v10.18.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
[INFO] DOCKER> Removing intermediate container 749d61ea9aeb
[ERROR] DOCKER> Unable to build image [uniknow/neurosim-ide:1.0] : "The command '/bin/sh -c yarn install' returned a non-zero code: 1"  ["The command '/bin/sh -c yarn install' returned a non-zero code: 1" ]
```

**To Reproduce**

1. Start creation of docker container by executing `./mvnw install`

**Expected behavior**

Finish maven build successfully

**Environment (please complete the following information):**
 - IDE type/version: Command line 
 - OS: MacOS Catalina 10.15.7

**Comment by msche** [comment]
Seems there where some cached files that caused the issue. By cleaning the workspace (`./mvnw clean`) then issue was fixed.
